version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.1

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: java --version
      - run: gradle

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit