version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.1

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: java --version
      - run: gradle

      - run:
        name: Creating Dummy Artifacts
        command: |
          echo "my artifact file" > /tmp/art-1;
          mkdir /tmp/artifacts;
          echo "my artifact files in a dir" > /tmp/artifacts/art-2;
    - store_artifacts:
        path: /tmp/art-1
        destination: artifact-file
    - store_artifacts:
        path: /tmp/artifacts